import Header from "@/components/navigations/Header";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { getNavigation } from "@/lib/sanity.client";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "HomeCare",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	const header = await getNavigation();

	return (
		<html lang='en'>
			<body className={inter.className}>
				<Header header={header} />
				<main>{children}</main>
			</body>
		</html>
	);
}
